trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UnityTestTask@1
  inputs:
    testMode: 'EditMode'
    unityEditorsPathMode: 'unityHub'
    commandLineArgumentsMode: 'custom'
    customCommandLineArguments: '-buildassetbundles'