trigger:
- master

pool:
  vmImage: 'windows-latest'

jobs:
- job: 'BuildAssetBundles'
  steps:
   - task: UnityTestTask@1
     inputs:
      testMode: 'EditMode'
      unityEditorsPathMode: 'unityHub'
      commandLineArgumentsMode: 'custom'
      customCommandLineArguments: '-buildassetbundles'